### ISSUE TITLE
Deprecation warning on later versions of node

### ISSUE THREAD

**Issue by minrwhite** [hoodiehq/pouchdb-admins#20]
When running the tests, a warning message is displayed:

    <snip>
        ✔ .get("kim") fails with not_found
    (node:13873) DeprecationWarning: crypto.pbkdf2 without specifying a digest is deprecated. Please specify a digest
        ✔ sets admin "kim" with password "secret"
    </snip>

This is due to the call in [lib/utils/hash-password.js](../blob/6ec1b58f46240bb28377a7dcdb1e8297bf679c53/lib/utils/hash-password.js#L6) that currently does not specify the digest.

As this parameter was introduced in io.js v1.0.0 / nodejs v4.0.0 it will be necessary to either detect the version and send appropriate parameters, or enforce a minimum node version in the package requirements.

Additionally, a digest method needs selecting. As the digest has not been specified up to now, and SHA1 is the default when the digest has been an optional parameter, it is most likely appropriate to select this for now; and then increase to a more secure digest (stored alongside the hash) when it is more appropriate to introduce breaking changes.

**Comment by minrwhite** [comment]
I would suggest that enforcing the minimum version of node as v4 would be the better option, as this is already done in [hoodie-server](/hoodiehq/hoodie-server/blob/b7bbaa4b33b070e56e3abbdb2443a878ce3651f9/package.json#L14) which depends on this package.

**Comment by gr2m** [comment]
fwiw we officially no longer support node < v4 as these versions are no longer maintained. Feel free to add require node v4 but no need to I’d say.
